### ISSUE TITLE
selectedItems array remains blank for table when user tries to click on checkbox with pressed "ctrl" button in window and "option" button in mac .

### ISSUE THREAD

**Issue by prahangd** [ciena-frost/ember-frost-table#53]
1. SelectedItems array remains blank for table when user tries to click on checkbox with pressed "ctrl" button in window and "option" button in mac .
2. Although checkbox gets selected when user tries to select  the record with ctrl button pressed in window and and "option" button in mac but selectedItems array  remains blank.
<img width="597" alt="screen shot 2018-02-08 at 3 44 52 pm" src="https://user-images.githubusercontent.com/13661364/35967500-123fc452-0ce7-11e8-9d4e-80417b183a9a.png">
<img width="862" alt="screen shot 2018-02-08 at 3 45 52 pm" src="https://user-images.githubusercontent.com/13661364/35967549-2ffa408a-0ce7-11e8-9689-88421417647c.png">

**Comment by juwara0** [comment]
@prahangd - Thank you for opening an issue to track this. Can you provide the following details about this issue:
 
* Where is this occurring in an app or when used inside another add-on? 
* What version of Ember CLI are you using when consuming this add-on?
* What version of Ember are you using when consuming this add-on?
* What version of this repo (`ember-frost-table`) are you using?
  * Please run `npm ls <package-name>` in the terminal in the directory for the code base where you are seeing this to gather that information.
* Can you point us to an instance of code where this is occurring so we can see the full setup that is in place?

**Comment by prahangd** [comment]
Where is this occurring in an app or when used inside another add-on? --> It occuring in all MCP pages where ember-frost-table is used.
What version of Ember CLI are you using when consuming this add-on? --> "ember-cli": "2.12.3",
What version of this repo (ember-frost-table) are you using? --> "ember-frost-table": "^2.0.0"

**Comment by notmessenger** [comment]
@prahangd On the MacOS the correct modifier/meta key you want to use is the `command ⌘` key, not `option`.  If you use the `command ⌘` key I believe you will find that things work as expected.

That being said, I have opened #54 because it is incorrect behavior that the use of `option` key should cause part of the intended behavior to function incorrectly.
